version: '3.8'

services:
  htx-bot:
    build: .
    container_name: htx_telegram_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - TZ=Asia/Shanghai
    networks:
      - bot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  redis:
    image: redis:alpine
    container_name: htx_bot_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  redis-data:
